name: npt
description: "NPT - A powerful Flutter App Drawer/Launcher application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2
  
  # Device Apps & Package Info
  device_apps: ^2.2.0
  package_info_plus: ^8.0.0
  
  # Persistent Storage
  shared_preferences: ^2.2.3
  
  # Utilities
  collection: ^1.18.0
  
  # UI Components
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.2

flutter:
  uses-material-design: true

  # Optional: Add custom assets
  # assets:
  #   - images/
  
  # Optional: Add custom fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf 